parameters:
  origammi.ez_app.manager.admin_user.id: 14

services:
  origammi.ez_app.repository.api:
      class: Origammi\Bundle\EzAppBundle\Repository\ApiService
      arguments:
          - "@ezpublish.query_type.registry"
      calls:
          - [setSearchService, ["@ezpublish.api.service.search"]]
          - [setLocationService, ["@origammi.ez_app.repository.location_api"]]
          - [setContentService, ["@origammi.ez_app.repository.content_api"]]
          - [setContentTypeService, ["@origammi.ez_app.repository.content_type_api"]]

  origammi.ez_app.repository.content_api:
      class: Origammi\Bundle\EzAppBundle\Repository\ContentApiService
      arguments:
          - "@ezpublish.api.service.content"
          - "@ezpublish.api.service.search"

  origammi.ez_app.repository.location_api:
      class: Origammi\Bundle\EzAppBundle\Repository\LocationApiService
      arguments:
          - "@ezpublish.api.service.location"
          - "@ezpublish.api.service.search"

  origammi.ez_app.repository.content_type_api:
      class: Origammi\Bundle\EzAppBundle\Repository\ContentTypeApiService
      arguments:
          - "@ezpublish.api.service.content_type"


  ##
  # Managers
  #
  origammi.ez_app.manager.abstract:
      abstract: true
      class: Origammi\Bundle\EzAppBundle\Manager\AbstractManager
      arguments:
          - "%origammi.ez_app.manager.admin_user.id%"
          - "%origammi.ez_app.main_language_code%"
      calls:
          - ['setRepository', ['@ezpublish.api.repository']]

  origammi.ez_app.manager.user:
      parent: origammi.ez_app.manager.abstract
      class: Origammi\Bundle\EzAppBundle\Manager\UserManager


  ##
  # Services
  #
  origammi.ez_app.service.language_resolver:
      class: Origammi\Bundle\EzAppBundle\Service\LanguageResolver
      arguments:
          - "%origammi.ez_app.main_language_code%"
          - "%ezpublish.siteaccesses_by_language%"
          - "@ezpublish.config.resolver"
      calls:
          - ['setSiteAccess', ['@ezpublish.siteaccess']]
          - ['setLocaleConverter', ['@ezpublish.locale.converter']]


  origammi.ez_app.service.content_type_resolver:
      class: Origammi\Bundle\EzAppBundle\Service\ContentTypeResolver
      arguments:
          - "@origammi.ez_app.repository.content_type_api"

  origammi.ez_app.service.field_resolver:
      class: Origammi\Bundle\EzAppBundle\Service\FieldResolver
      arguments:
          - "@ezpublish.field_helper"
          - "@ezpublish.fieldtype.ezrichtext.converter.output.xhtml5"
          - "@ezpublish.fieldtype.ezimage.variation_service"
          - "@ezpublish.translation_helper"


  origammi.ez_app.service.location_resolver:
      class: Origammi\Bundle\EzAppBundle\Service\LocationResolver
      arguments:
          - "@origammi.ez_app.repository.location_api"
          - "@ezpublish.templating.global_helper"


  ##
  # Twig helpers
  #
  origammi.ez_app.twig.extension.core:
      class: Origammi\Bundle\EzAppBundle\Twig\Extension\CoreExtension
      arguments: ["@origammi.ez_app.repository.content_api"]
      tags:
          - {name: twig.extension}

  origammi.ez_app.twig.content_extension:
      class: Origammi\Bundle\EzAppBundle\Twig\ContentExtension
      arguments:
        - '@origammi.ez_app.repository.content_api'
        - '@origammi.ez_app.service.content_type_resolver'
        - '@origammi.ez_app.service.field_resolver'
      tags:
          - { name: twig.extension }

  origammi.ez_app.twig.location_extension:
      class: Origammi\Bundle\EzAppBundle\Twig\LocationExtension
      arguments:
        - '@origammi.ez_app.repository.location_api'
      tags:
          - { name: twig.extension }

  ##
  # Controllers
  #
  origammi.ez_app.controller.language_switcher:
          class: Origammi\Bundle\EzAppBundle\Controller\LanguageSwitcherController
          arguments:
              - "@origammi.ez_app.service.language_resolver"
              - "@ezpublish.controller.content.view"
